### ISSUE TITLE
debug.log ERROR: Coremod EyeOfDragonsPlugin: Unable to class load the plugin EyeOfDragonsPlugin

### ISSUE THREAD

**Issue by Krutoy242** [MKuckert/eye-of-dragons#4]
Game output this lines in `debug.log`:

```zs
[15:34:47] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in eyeofdragons-0.0.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[15:34:47] [main/DEBUG] [FML]: Instantiating coremod class EyeOfDragonsPlugin
[15:34:47] [main/ERROR] [FML]: Coremod EyeOfDragonsPlugin: Unable to class load the plugin de.curlybracket.eyeofdragons.EyeOfDragonsPlugin
java.lang.ClassNotFoundException: de.curlybracket.eyeofdragons.EyeOfDragonsPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_251]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_251]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) [forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) [forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) [forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) [forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) [forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) [forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) [forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

But, seems like mod is working fine anyway.
What is this means, and how to avoid errors?

**Comment by darchitectlp** [comment]
Also seeing this error.

**Comment by Krutoy242** [comment]
Question still actual!

**Comment by Scusemua** [comment]
Still seeing the error myself!

**Comment by gwynhefar** [comment]
Still seeing this error.  Is the mod dead?

**Comment by Scusemua** [comment]
> Is the mod dead?

Well, it looks like the last commit/update to the repository with 3-4 years ago, so this may well be the case.
